version: '3.1'

services:
  
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: testtask
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:8080:80
    environment:
      - PMA_ARBITRARY=1

  phpfpm:
    depends_on:
      - db
    image: 'bitnami/php-fpm:latest'
    command: sh -c "bash < /php-init/init.sh"
    links:
      - db:mysql
    volumes:
      - ./wp1:/var/www/wp1
      - ./wp2:/var/www/wp2
      - ./php-init:/php-init:ro  

  nginx:
    image: 'nginx:latest'
    depends_on:
      - phpfpm
      - certbot
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./wp1:/var/www/wp1
      - ./wp2:/var/www/wp2  

  certbot:
    image: certbot/certbot:latest
    entrypoint: sh -c "certbot renew && echo \"Nothing to renew, exitting...\" && exit 0"
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot:/docker-entrypoint.d:ro
